filegroup(
    name = "dynasm",
    srcs = [
        "dynasm.lua",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "dasm_lua",
    srcs = glob(["dasm*.lua"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "dasm_h",
    srcs = glob(["dasm*.h"]),
    visibility = ["//visibility:public"],
)
